name = "BankSim"
uuid = "17a1c2e5-945c-44cf-ae99-afac244dc9b2"
authors = ["Suraj Pattar <pattarsuraj@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
